<?php

declare (strict_types=1);

return [
    'folder' => [
        'base' => './img/galeria/',
        'full' => ['folder' => 'full', 'suffix' => '-900'],
        'miniatura' => ['folder' => 'miniaturas/', 'suffix' => '-360'],
    ],
    'imagenes' => [
        ['nombre' => 'image-0001', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0002', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0003', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0004', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0005', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0006', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0007', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0008', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0009', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0010', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0011', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0012', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0013', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0014', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0015', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0016', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0017', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0018', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0019', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0020', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0021', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0022', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0023', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0024', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0025', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0026', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0027', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0028', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0029', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0030', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0031', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0032', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0033', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0034', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0035', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0036', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0037', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0038', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0039', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0040', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0041', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0042', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0043', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0044', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0045', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0046', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0047', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0048', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0049', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0050', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0051', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0052', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0053', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0054', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0055', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0056', 'alt' => 'Texto de la imagen'],
        ['nombre' => 'image-0057', 'alt' => 'Texto de la imagen'],
    ]
];
